[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=advapi32.lib"]
[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=advapi32.lib"]

